// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6CA0RxmY_Bv0BJ24NM-sBibR94nFZC7o',
    appId: '1:80947765845:web:c8cf200224fb0e7fa0aadc',
    messagingSenderId: '80947765845',
    projectId: 'attendance-project-9a978',
    authDomain: 'attendance-project-9a978.firebaseapp.com',
    storageBucket: 'attendance-project-9a978.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrlvjNwIiHkKJD556gKXCVaV1cZHFB290',
    appId: '1:80947765845:android:df1612d2b03a3733a0aadc',
    messagingSenderId: '80947765845',
    projectId: 'attendance-project-9a978',
    storageBucket: 'attendance-project-9a978.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFD01ITSakUjMfr62BsfZrQw6tF_r3i3I',
    appId: '1:80947765845:ios:cb75d8d4e4afea47a0aadc',
    messagingSenderId: '80947765845',
    projectId: 'attendance-project-9a978',
    storageBucket: 'attendance-project-9a978.firebasestorage.app',
    iosBundleId: 'com.example.mobileApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFD01ITSakUjMfr62BsfZrQw6tF_r3i3I',
    appId: '1:80947765845:ios:cb75d8d4e4afea47a0aadc',
    messagingSenderId: '80947765845',
    projectId: 'attendance-project-9a978',
    storageBucket: 'attendance-project-9a978.firebasestorage.app',
    iosBundleId: 'com.example.mobileApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6CA0RxmY_Bv0BJ24NM-sBibR94nFZC7o',
    appId: '1:80947765845:web:5b496ef6f072233aa0aadc',
    messagingSenderId: '80947765845',
    projectId: 'attendance-project-9a978',
    authDomain: 'attendance-project-9a978.firebaseapp.com',
    storageBucket: 'attendance-project-9a978.firebasestorage.app',
  );
}
